defaults: 
  - clients: 10_clients_a9a

dataset_name: "a9a"
train_ratio: .75
task_type: "BINARY"


metric:
  name: "Accuracy"
  fn:
    _target_: torchmetrics.Accuracy
    task: "binary"

criterion:
  _target_: torch.nn.BCELoss

xgb:
  _target_:  xgboost.XGBClassifier
  objective: "binary:logistic"
  max_depth: 8
CNN:
  lr: ${clients.k}