dataset_name: "a9a"
train_ratio: .75
task_type: "BINARY"
n_estimators_client: 100
num_rounds: 30
client_num: 5

metric:
  name: "Accuracy"
  fn:
    _target_: torchmetrics.Accuracy
    task: "binary"

criterion:
  _target_: torch.nn.BCELoss

xgb:
  _target_:  xgboost.XGBClassifier
  objective: "binary:logistic"
  max_depth: 8
CNN:
  lr: .0005