dataset_name: "cod-rna"
train_ratio: .75
task_type: "BINARY"
n_estimators_client: 100
num_rounds: 30

metric:
  name: "Accuracy"
  fn:
    _target_: torchmetrics.Accuracy
    task: "binary"

criterion:
  _target_: torch.nn.BCELoss

xgb:
  _target_:  xgboost.XGBRegressor
  objective: "reg:squarederror"
  max_depth: 8
CNN:
  lr: .0001