dataset_name: "cpusmall"
train_ratio: .75
task_type: "REG"
n_estimators_client: 100
num_rounds: 30
client_num: 5


metric:
  name: "mse"
  fn:
    _target_: torchmetrics.MeanSquaredError

criterion:
  _target_: torch.nn.MSELoss


xgb:
  _target_:  xgboost.XGBRegressor
  objective: "reg:squarederror"
  max_depth: 8
CNN:
  lr: .0001